[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npx prisma generate"

[deploy]
startCommand = "cd backend && npx prisma generate && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[phases.setup]
cmds = ["cd backend"]

[phases.build]
cmds = ["cd backend", "npm install", "npx prisma generate"]

[phases.start]
cmds = ["cd backend", "npx prisma generate", "npm start"]

# Specify engines
[nixpacks]
node-version = "18"

[[services]]
internal_port = 5003
protocol = "http"

[envs]
NODE_ENV = "production" 